resolver: lts-13.0

packages:
- .

extra-deps:
- polysemy-0.7.0.0
- type-errors-0.2.0.0
- polysemy-plugin-0.2.1.0
- th-abstraction-0.3.1.0
- bifunctors-5.5.4
- first-class-families-0.5.0.0
- unagi-chan-0.4.1.0

